export const data = [
    {
        id: 1,
        movieName: "Forrest Gump",
        releaseDate: new Date(1994, 6, 6),
        genre: "Drama, Romance",
        ratingIMDB: 8.8,
        description: "The story of Forrest Gump, a simple man with a low IQ but good intentions, who unwittingly influences several historical events in the 20th century United States.",
        starring: ["Tom Hanks", "Robin Wright", "Gary Sinise", "Mykelti Williamson"],
        directedBy: "Robert Zemeckis",
        duration: 142,
        imgUrl: "https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg"
    },
    {
        id: 2,
        movieName: "Harry Potter and the Sorcerer's Stone",
        releaseDate: new Date(2001, 10, 16),
        genre: "Adventure, Family, Fantasy",
        ratingIMDB: 7.6,
        description: "An orphaned boy enrolls in a school of wizardry, where he learns the truth about himself, his family, and the terrible evil that haunts the magical world.",
        starring: ["Daniel Radcliffe", "Rupert Grint", "Emma Watson", "Richard Harris"],
        directedBy: "Chris Columbus",
        duration: 152,
        imgUrl: "https://image.tmdb.org/t/p/w500/tOEOlmLP3U4nHYqql1jY3AX9dPi.jpg"
    },
    {
        id: 3,
        movieName: "The Shawshank Redemption",
        releaseDate: new Date(1994, 9, 23),
        genre: "Drama",
        ratingIMDB: 9.3,
        description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        starring: ["Tim Robbins", "Morgan Freeman", "Bob Gunton", "William Sadler"],
        directedBy: "Frank Darabont",
        duration: 142,
        imgUrl: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg"
    },
    {
        id: 4,
        movieName: "Inception",
        releaseDate: new Date(2010, 6, 16),
        genre: "Action, Adventure, Sci-Fi",
        ratingIMDB: 8.8,
        description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        starring: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
        directedBy: "Christopher Nolan",
        duration: 148,
        imgUrl: "https://image.tmdb.org/t/p/w500/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg"
    },
    {
        id: 5,
        movieName: "One Flew Over the Cuckoo's Nest",
        releaseDate: new Date(1975, 10, 19),
        genre: "Drama",
        ratingIMDB: 8.7,
        description: "A criminal pleads insanity and is admitted to a mental institution, where he rebels against the oppressive nurse and rallies up the scared patients.",
        starring: ["Jack Nicholson", "Louise Fletcher", "Michael Berryman", "Peter Brocco"],
        directedBy: "Milos Forman",
        duration: 133,
        imgUrl: "https://image.tmdb.org/t/p/w500/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg"
    },
    {
        id: 6,
        movieName: "Das Boot",
        releaseDate: new Date(1981, 8, 17),
        genre: "Drama, War",
        ratingIMDB: 8.3,
        description: "The claustrophobic world of a WWII German U-boat; boredom, filth, and sheer terror.",
        starring: ["Jürgen Prochnow", "Herbert Grönemeyer", "Klaus Wennemann", "Hubertus Bengsch"],
        directedBy: "Wolfgang Petersen",
        duration: 149,
        imgUrl: "https://image.tmdb.org/t/p/w500/mgX9sExDcdwRx8YxPjL8ngfSTmn.jpg"
    },
    {
        id: 7,
        movieName: "The Godfather",
        releaseDate: new Date(1972, 2, 24),
        genre: "Crime, Drama",
        ratingIMDB: 9.2,
        description: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        starring: ["Marlon Brando", "Al Pacino", "James Caan", "Richard S. Castellano"],
        directedBy: "Francis Ford Coppola",
        duration: 175,
        imgUrl: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg"
    },
    {
        id: 8,
        movieName: "The Dark Knight",
        releaseDate: new Date(2008, 6, 18),
        genre: "Action, Crime, Drama",
        ratingIMDB: 9.0,
        description: "When the menace known as The Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham. The Dark Knight must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        starring: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
        directedBy: "Christopher Nolan",
        duration: 152,
        imgUrl: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg"
    },
    {
        id: 9,
        movieName: "Pulp Fiction",
        releaseDate: new Date(1994, 9, 10),
        genre: "Crime, Drama",
        ratingIMDB: 8.9,
        description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        starring: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
        directedBy: "Quentin Tarantino",
        duration: 154,
        imgUrl: "https://image.tmdb.org/t/p/w500/dM2w364MScsjFf8pfMbaWUcWrR.jpg"
    },
    {
        id: 10,
        movieName: "Fight Club",
        releaseDate: new Date(1999, 9, 10),
        genre: "Drama",
        ratingIMDB: 8.8,
        description: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
        starring: ["Brad Pitt", "Edward Norton", "Meat Loaf", "Zach Grenier"],
        directedBy: "David Fincher",
        duration: 139,
        imgUrl: "https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg"
    },
    {
        id: 11,
        movieName: "The Matrix",
        releaseDate: new Date(1999, 2, 31),
        genre: "Action, Sci-Fi",
        ratingIMDB: 8.7,
        description: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
        starring: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss", "Hugo Weaving"],
        directedBy: "Lana Wachowski, Lilly Wachowski",
        duration: 136,
        imgUrl: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg"
    },
    {
        id: 12,
        movieName: "Goodfellas",
        releaseDate: new Date(1990, 8, 12),
        genre: "Biography, Crime, Drama",
        ratingIMDB: 8.7,
        description: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
        starring: ["Robert De Niro", "Ray Liotta", "Joe Pesci", "Lorraine Bracco"],
        directedBy: "Martin Scorsese",
        duration: 146,
        imgUrl: "https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg"
    },
    {
        id: 13,
        movieName: "The Lord of the Rings: The Fellowship of the Ring",
        releaseDate: new Date(2001, 11, 19),
        genre: "Action, Adventure, Drama",
        ratingIMDB: 8.8,
        description: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
        starring: ["Elijah Wood", "Ian McKellen", "Orlando Bloom", "Sean Bean"],
        directedBy: "Peter Jackson",
        duration: 178,
        imgUrl: "https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg"
    },
    {
        id: 14,
        movieName: "Star Wars: Episode IV - A New Hope",
        releaseDate: new Date(1977, 4, 25),
        genre: "Action, Adventure, Fantasy",
        ratingIMDB: 8.6,
        description: "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader.",
        starring: ["Mark Hamill", "Harrison Ford", "Carrie Fisher", "Alec Guinness"],
        directedBy: "George Lucas",
        duration: 121,
        imgUrl: "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg"
    },
    {
        id: 15,
        movieName: "The Lion King",
        releaseDate: new Date(1994, 5, 15),
        genre: "Animation, Adventure, Drama",
        ratingIMDB: 8.5,
        description: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
        starring: ["Matthew Broderick", "Jeremy Irons", "James Earl Jones", "Whoopi Goldberg"],
        directedBy: "Roger Allers, Rob Minkoff",
        duration: 88,
        imgUrl: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg"
    },
    {
        id: 16,
        movieName: "The Silence of the Lambs",
        releaseDate: new Date(1991, 1, 14),
        genre: "Crime, Drama, Thriller",
        ratingIMDB: 8.6,
        description: "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
        starring: ["Jodie Foster", "Anthony Hopkins", "Lawrence A. Bonney", "Kasi Lemmons"],
        directedBy: "Jonathan Demme",
        duration: 118,
        imgUrl: "https://image.tmdb.org/t/p/w500/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg"
    },
    {
        id: 17,
        movieName: "Schindler's List",
        releaseDate: new Date(1993, 11, 15),
        genre: "Biography, Drama, History",
        ratingIMDB: 8.9,
        description: "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce after witnessing their persecution by the Nazis.",
        starring: ["Liam Neeson", "Ralph Fiennes", "Ben Kingsley", "Caroline Goodall"],
        directedBy: "Steven Spielberg",
        duration: 195,
        imgUrl: "https://image.tmdb.org/t/p/w500/c8Ass7acuOe4za6DhSattE359gr.jpg"
    },
    {
        id: 18,
        movieName: "The Green Mile",
        releaseDate: new Date(1999, 11, 10),
        genre: "Crime, Drama, Fantasy",
        ratingIMDB: 8.6,
        description: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
        starring: ["Tom Hanks", "Michael Clarke Duncan", "David Morse", "Bonnie Hunt"],
        directedBy: "Frank Darabont",
        duration: 189,
        imgUrl: "https://image.tmdb.org/t/p/w500/3yJUlOtVa09CYJocwBU8eAryja0.jpg"
    },
    {
        id: 19,
        movieName: "Saving Private Ryan",
        releaseDate: new Date(1998, 6, 24),
        genre: "Drama, War",
        ratingIMDB: 8.6,
        description: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.",
        starring: ["Tom Hanks", "Matt Damon", "Tom Sizemore", "Edward Burns"],
        directedBy: "Steven Spielberg",
        duration: 169,
        imgUrl: "https://image.tmdb.org/t/p/w500/miDoEMlYDJhOCvxlzI0wZqBs9Yt.jpg"
    },
    {
        id: 20,
        movieName: "Interstellar",
        releaseDate: new Date(2014, 10, 26),
        genre: "Adventure, Drama, Sci-Fi",
        ratingIMDB: 8.6,
        description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        starring: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Mackenzie Foy"],
        directedBy: "Christopher Nolan",
        duration: 169,
        imgUrl: "https://image.tmdb.org/t/p/w500/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg"
    },
    {
        id: 21,
        movieName: "Parasite",
        releaseDate: new Date(2019, 4, 30),
        genre: "Comedy, Drama, Thriller",
        ratingIMDB: 8.6,
        description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
        starring: ["Kang-ho Song", "Sun-kyun Lee", "Yeo-jeong Cho", "Woo-sik Choi"],
        directedBy: "Bong Joon Ho",
        duration: 132,
        imgUrl: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg"
    },
    {
        id: 22,
        movieName: "Gladiator",
        releaseDate: new Date(2000, 4, 5),
        genre: "Action, Adventure, Drama",
        ratingIMDB: 8.5,
        description: "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
        starring: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen", "Oliver Reed"],
        directedBy: "Ridley Scott",
        duration: 155,
        imgUrl: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg"
    },
    {
        id: 23,
        movieName: "The Prestige",
        releaseDate: new Date(2006, 9, 20),
        genre: "Drama, Mystery, Sci-Fi",
        ratingIMDB: 8.5,
        description: "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything they have to outwit each other.",
        starring: ["Christian Bale", "Hugh Jackman", "Scarlett Johansson", "Michael Caine"],
        directedBy: "Christopher Nolan",
        duration: 130,
        imgUrl: "https://image.tmdb.org/t/p/w500/5MXyQfz8xUP3dIFPTubhTsbFY6N.jpg"
    },
    {
        id: 24,
        movieName: "The Departed",
        releaseDate: new Date(2006, 9, 26),
        genre: "Crime, Drama, Thriller",
        ratingIMDB: 8.5,
        description: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
        starring: ["Leonardo DiCaprio", "Matt Damon", "Jack Nicholson", "Mark Wahlberg"],
        directedBy: "Martin Scorsese",
        duration: 151,
        imgUrl: "https://image.tmdb.org/t/p/w500/tGLO9zw5ZtCeyyEWgbYGgsFxC6i.jpg"
    },
    {
        id: 25,
        movieName: "Whiplash",
        releaseDate: new Date(2014, 9, 10),
        genre: "Drama, Music",
        ratingIMDB: 8.5,
        description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
        starring: ["Miles Teller", "J.K. Simmons", "Melissa Benoist", "Paul Reiser"],
        directedBy: "Damien Chazelle",
        duration: 106,
        imgUrl: "https://image.tmdb.org/t/p/w500/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg"
    },
    {
        id: 26,
        movieName: "The Intouchables",
        releaseDate: new Date(2011, 10, 2),
        genre: "Biography, Comedy, Drama",
        ratingIMDB: 8.5,
        description: "After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.",
        starring: ["François Cluzet", "Omar Sy", "Anne Le Ny", "Audrey Fleurot"],
        directedBy: "Olivier Nakache, Éric Toledano",
        duration: 112,
        imgUrl: "https://image.tmdb.org/t/p/w500/wMS0hALh4z6me9oKpUWLALkNJtQ.jpg"
    },
    {
        id: 27,
        movieName: "Back to the Future",
        releaseDate: new Date(1985, 6, 3),
        genre: "Adventure, Comedy, Sci-Fi",
        ratingIMDB: 8.5,
        description: "Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend, the eccentric scientist Doc Brown.",
        starring: ["Michael J. Fox", "Christopher Lloyd", "Lea Thompson", "Crispin Glover"],
        directedBy: "Robert Zemeckis",
        duration: 116,
        imgUrl: "https://image.tmdb.org/t/p/w500/pTpxQB1N0waaSc3OSn0e9oc8kx9.jpg"
    },
    {
        id: 28,
        movieName: "Se7en",
        releaseDate: new Date(1995, 8, 22),
        genre: "Crime, Drama, Mystery",
        ratingIMDB: 8.6,
        description: "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
        starring: ["Morgan Freeman", "Brad Pitt", "Kevin Spacey", "Andrew Kevin Walker"],
        directedBy: "David Fincher",
        duration: 127,
        imgUrl: "https://image.tmdb.org/t/p/w500/69Sns8WoET6CfaYlIkHbla4l7nC.jpg"
    },
    {
        id: 29,
        movieName: "The Usual Suspects",
        releaseDate: new Date(1995, 7, 19),
        genre: "Crime, Drama, Mystery",
        ratingIMDB: 8.5,
        description: "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.",
        starring: ["Kevin Spacey", "Gabriel Byrne", "Chazz Palminteri", "Stephen Baldwin"],
        directedBy: "Bryan Singer",
        duration: 106,
        imgUrl: "https://image.tmdb.org/t/p/w500/bUPmtQzrRhzqYySeiMpv7GurAfm.jpg"
    },
    {
        id: 30,
        movieName: "Braveheart",
        releaseDate: new Date(1995, 4, 18),
        genre: "Biography, Drama, History",
        ratingIMDB: 8.3,
        description: "Scottish warrior William Wallace leads his countrymen in a rebellion to free his homeland from the tyranny of King Edward I of England.",
        starring: ["Mel Gibson", "Sophie Marceau", "Patrick McGoohan", "Angus Macfadyen"],
        directedBy: "Mel Gibson",
        duration: 178,
        imgUrl: "https://image.tmdb.org/t/p/w500/or1gBugydmjToAEq7OZY0owwFk.jpg"
    },
    {
        id: 31,
        movieName: "The Pianist",
        releaseDate: new Date(2002, 8, 24),
        genre: "Biography, Drama, Music",
        ratingIMDB: 8.5,
        description: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto of World War II.",
        starring: ["Adrien Brody", "Thomas Kretschmann", "Frank Finlay", "Emilia Fox"],
        directedBy: "Roman Polanski",
        duration: 150,
        imgUrl: "https://image.tmdb.org/t/p/w500/2hFvxCCWrYmMDC6GxfHrYt0iYFy.jpg"
    },
    {
        id: 32,
        movieName: "Terminator 2: Judgment Day",
        releaseDate: new Date(1991, 6, 1),
        genre: "Action, Sci-Fi",
        ratingIMDB: 8.5,
        description: "A cyborg, identical to the one who failed to kill Sarah Connor, must now protect her teenage son, John Connor, from a more advanced and powerful cyborg.",
        starring: ["Arnold Schwarzenegger", "Linda Hamilton", "Edward Furlong", "Robert Patrick"],
        directedBy: "James Cameron",
        duration: 137,
        imgUrl: "https://image.tmdb.org/t/p/w500/weVXMD5QBGeQil4HEATZqAkXeEc.jpg"
    }
];
